# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
name: $(version.major).$(version.minor).$(Rev:r)

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:

- task: UseDotNet@2
  displayName: 'Install dotnet core SDK 3.0.100'
  inputs:
    version: '3.0.100'

- task: DotNetCoreCLI@2
  displayName: Install dotnet-ef 3.0.0
  inputs:
    command: 'custom'
    custom: 'tool'
    arguments: 'install --global dotnet-ef --version 3.0.0'
    
- task: DotNetCoreCLI@2
  displayName: 'Create database update script'
  inputs:  
    command: 'custom'
    custom: 'ef migrations script'
    arguments: '--project=./Fmas12d.Api/Fmas12d.Api.csproj -i -o ./Deployment/AimesUat/Fmas12d.Api/update.sql'

- task: DotNetCoreCLI@2
  displayName: 'Fmas12d.Api - Create Deployment'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: './Fmas12d.Api/Fmas12d.Api.csproj'
    zipAfterPublish: false
    modifyOutputPath: false
    arguments: '-c AimesUat -r win-x64 --output ./Deployment/AimesUat/Fmas12d.Api -p:Version=$(build.buildNumber)'

- task: Npm@1
  displayName: 'Fmas12d.Ui - Install npm packages'
  inputs:
    command: 'install'
    workingDir: './Fmas12d.Ui'

- task: Npm@1
  displayName: "Fmas12d.Ui - Set the version number"
  inputs:
    command: 'custom'
    workingDir: './Fmas12d.Ui'
    customCommand: 'version $(build.buildNumber) --force'

- task: Npm@1
  displayName: "Fmas12d.Ui - Create deployment"
  inputs:
    command: 'custom'
    workingDir: './Fmas12d.Ui'
    customCommand: 'run build:aimes-uat'

- task: Npm@1
  displayName: 'Fmas12d.Mobile - Install npm packages'
  inputs:
    command: 'install'
    workingDir: './Fmas12d.Mobile'

- task: Npm@1
  displayName: "Fmas12d.Mobile - Set the version number"
  inputs:
    command: 'custom'
    workingDir: './Fmas12d.Mobile'
    customCommand: 'version $(build.buildNumber) --force'    

- task: Npm@1
  displayName: "Fmas12d.Mobile - Check build completes successfully"
  inputs:
    command: 'custom'
    workingDir: './Fmas12d.Mobile'
    customCommand: 'run build:aimes-uat'

- task: PublishBuildArtifacts@1
  displayName: 'Fmas12d.Api - Publish build artifacts'
  inputs:
    PathtoPublish: './Deployment/AimesUat/Fmas12d.Api'
    ArtifactName: 'api'
    publishLocation: 'Container'

- task: PublishBuildArtifacts@1
  displayName: 'Fmas12d.Ui - Publish build artifacts'
  inputs:
    PathtoPublish: './Deployment/AimesUat/Fmas12d.Ui'
    ArtifactName: 'ui'
    publishLocation: 'Container'

- task: PublishBuildArtifacts@1
  displayName: 'Fmas12d.Mobile - Publish build artifacts'
  inputs:
    PathtoPublish: './Deployment/AimesUat/Fmas12d.Mobile'
    ArtifactName: 'mobile'
    publishLocation: 'Container'    