# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: UseDotNet@2
  displayName: 'Install dotnet core SDK 3.0.100'
  inputs:
    version: '3.0.100'

- task: DotNetCoreCLI@2
  displayName: Install dotnet-ef 3.0.0
  inputs:
    command: 'custom'
    custom: 'tool'
    arguments: 'install --global dotnet-ef --version 3.0.0'
    
- task: DotNetCoreCLI@2
  displayName: 'Create database update script'
  inputs:  
    command: 'custom'
    custom: 'ef'
    arguments: 'migrations script --project=./Fmas12d.Api/Fmas12d.Api.csproj -i'

- task: DotNetCoreCLI@2
  displayName: 'Fmas12d.Api - Check build completes successfully'
  inputs:
    projects: '**/*.csproj'
    arguments: '-c AimesUat -r win-x64'

- task: Npm@1
  displayName: 'Fmas12d.Ui - Install npm packages'
  inputs:
    command: 'install'
    workingDir: './Fmas12d.Ui'

- task: Npm@1
  displayName: "Fmas12d.Ui - Check build completes successfully"
  inputs:
    command: 'custom'
    workingDir: './Fmas12d.Ui'
    customCommand: 'run build:aimes-uat'

- task: Npm@1
  displayName: 'Fmas12d.Mobile - Install npm packages'
  inputs:
    command: 'install'
    workingDir: './Fmas12d.Mobile'

- task: Npm@1
  displayName: "Fmas12d.Mobile - Check build completes successfully"
  inputs:
    command: 'custom'
    workingDir: './Fmas12d.Mobile'
    customCommand: 'run build:aimes-uat'
    