export const DOCTORSTATUSSELECTED = 1;
export const DOCTORSTATUSACCEPTED = 2;
export const REFERRALSTATUSASSESSMENTSCHEDULED = 6;
export const AVAILABLE = 1;
export const UNAVAILABLE = 2;

export const PROFILETYPEDOCTOR = 3;
export const PROFILETYPEAMHP = 2;

export const ASSESSMENTSCHEDULED = 6;
export const ASSESSMENTRESCHEDULING = 7;
export const AWAITINGREVIEW = 8;

export const CLAIMSTATUSSUBMITTED = 1;
export const CLAIMSTATUSPROCESSING = 2;
export const CLAIMSTATUSQUERY = 3;
export const CLAIMSTATUSAPPROVED = 4;
export const CLAIMSTATUSAWAITING = 5;
export const CLAIMSTATUSREJECTED = 6;

export const KNOWN_LOCATION_OTHER_ID = -1;
export const KNOWN_LOCATION_OTHER_NAME = "Other";
