export const DOCTORSTATUSSELECTED = 1;
export const DOCTORSTATUSACCEPTED = 2;
export const REFERRALSTATUSASSESSMENTSCHEDULED = 6;
export const AVAILABLE = 1;
export const UNAVAILABLE = 2;

export const PROFILETYPEDOCTOR = 3;
export const PROFILETYPEAMHP = 2;
