export const DOCTORSTATUSSELECTED = 1;
export const DOCTORSTATUSACCEPTED = 2;
export const DOCTORSTATUSALLOCATED = 2;
export const REFERRALSTATUSASSESSMENTSCHEDULED = 6;
export const AVAILABLE = 1;
export const UNAVAILABLE = 2;

export const PROFILETYPEDOCTOR = 3;
export const PROFILETYPEAMHP = 2;

export const ASSESSMENTSCHEDULED = 6;
export const ASSESSMENTRESCHEDULING = 7;
export const AWAITINGREVIEW = 8;
export const REFERRALSTATUSOPEN = 10;

export const CLAIMSTATUSSUBMITTED = 1;
export const CLAIMSTATUSPROCESSING = 2;
export const CLAIMSTATUSQUERY = 3;
export const CLAIMSTATUSAPPROVED = 4;
export const CLAIMSTATUSAWAITING = 5;
export const CLAIMSTATUSREJECTED = 6;

export const KNOWN_LOCATION_OTHER_ID = -1;
export const KNOWN_LOCATION_OTHER_NAME = "Other";


export const REFERRALSTATUS_NEW = 1;
export const REFERRALSTATUS_SELECTING = 2;
export const REFERRALSTATUS_AWAITING_RESPONSES = 3;
export const REFERRALSTATUS_RESPONSES_PARTIAL = 4;
export const REFERRALSTATUS_RESPONSES_COMPLETE = 5;
export const REFERRALSTATUS_SCHEDULED = 6;
export const REFERRALSTATUS_RESCHEDULING = 7;
export const REFERRALSTATUS_AWAITING_REVIEW = 8;
export const REFERRALSTATUS_CLOSED = 9;
export const REFERRALSTATUS_OPEN = 10;
